FROM python:3.11-slim

RUN pip install flask flask-login reportlab

WORKDIR /app
COPY web-interface/ .

ENV VULNERABLE_HOST=vulnerable
ENV VULNERABLE_PORT=8080
ENV LDAP_HOST=ldap
ENV LDAP_PORT=1389

CMD ["python3", "app.py"]