version: '3.8'

services:
  lab-manager:
    build: .
    container_name: lab-manager
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - //var/run/docker.sock:/var/run/docker.sock  # Windows
      #- /var/run/docker.sock:/var/run/docker.sock  # Ubuntu
      - ../attacks:/attacks:ro                       # ← corrigé
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - lab-network

networks:
  lab-network:
    external: true   # ← juste external, pas de driver/name
    name: lab-network